kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-list
  namespace: frontend
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-list
  namespace: frontend
subjects:
  - kind: ServiceAccount
    name: default
    namespace: backend
roleRef:
  kind: ClusterRole
  name: cm-list
  apiGroup: rbac.authorization.k8s.io
