# Set the time to the interval you want to test and apply

apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test
  namespace: staging
spec:
  weekdays: "*"
  sleepAt: "22:15"
  wakeUpAt: "22:20"
  timeZone: "Europe/Rome"
---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test-prod
  namespace: production
spec:
  weekdays: "*"
  sleepAt: "22:20"
  wakeUpAt: "22:30"
  timeZone: "Europe/Rome"

---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test-prod-next
  namespace: production
spec:
  weekdays: "*"
  sleepAt: "00:10"
  wakeUpAt: "00:15"
  timeZone: "Europe/Rome"
---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test-prod-morning-except-node-app
  namespace: production
spec:
  weekdays: "*"
  sleepAt: "08:00"
  wakeUpAt: "10:00"
  timeZone: "Europe/Rome"
  excludeRef:
    - apiVersion: "apps/v1"
      kind: Deployment
      name: node-app
---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test-prod-afternoon-except-django-app
  namespace: production
spec:
  weekdays: "*"
  sleepAt: "13:00"
  wakeUpAt: "15:00"
  timeZone: "Europe/Rome"
  excludeRef:
    - apiVersion: "apps/v1"
      kind: Deployment
      name: django-app
---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test-staging-morning-except-django
  namespace: staging
spec:
  weekdays: "*"
  sleepAt: "09:00"
  wakeUpAt: "12:00"
  timeZone: "Europe/Rome"
  excludeRef:
    - apiVersion: "apps/v1"
      kind: Deployment
      name: django-app
---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: test-staging-afternoon-except-node
  namespace: staging
spec:
  weekdays: "*"
  sleepAt: "17:00"
  wakeUpAt: "18:30"
  timeZone: "Europe/Rome"
  excludeRef:
    - apiVersion: "apps/v1"
      kind: Deployment
      name: node-app

