apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - generated/mongo.yml
  - generated/redis.yml
  - apps/django.yml
  - apps/node.yml
patches:
  - path: patch.yml
    target:
      kind: Deployment