apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: production
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: ghcr.io/kube-greeners/infrastructure/django:latest
          name: django
          ports:
            - containerPort: 8000
              name: app
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000